config/routes.rb
Rails.application.routes.draw do
  get 'utilisateurs/new'

  root 'statique#accueil'

  get '/contact', to: 'statique#contact'

  get '/team', to: 'statique#team'

  get '/services', to: 'statique#services'

  get '/signup', to: 'utilisateurs#new'

  resources :utilisateurs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/utilisateur.rb
class Utilisateur < ApplicationRecord
	before_save {self.email = email.downcase}

	validates :nom, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\Z/i
	validates :email, presence: true, length: { maximum: 244 },
					format: { with: VALID_EMAIL_REGEX },
					uniqueness: {case_sensitive:  false}
	validates :password, presence: true, length: { minimum: 6 }
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def premier
    render html: "Bonjour tout le monde"
  end
end

app/controllers/statique_controller.rb
class StatiqueController < ApplicationController
  def accueil
  end

  def contact
  end

  def team
  end

  def services
  end
end

app/controllers/utilisateurs_controller.rb
class UtilisateursController < ApplicationController
  def new
    @utilisateur = Utilisateur.new
  end
  
  def show
    @utilisateur = Utilisateur.find(params[:id])
  end

  def create
    @utilisateur = Utilisateur.new(utilisateur_params)# On crée une autre fonction car si on utilise params[] > permet à n'importe qui d'avoir des droits administrateurs
    if @utilisateur.save
      # Sauvegarde confirmé <- True
      flash[:success] = "Bienvenue sur le clone de Twitter !"
      redirect_to @utilisateur
    else
      render "new"
    end
    
  end

  private 

  def utilisateur_params
    params.require(:utilisateur).permit(:nom, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statique_helper.rb
module StatiqueHelper
    def full_title(page_title = " ")
        base_title = "Tutoriel RoR Udemy"
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end
    end
end

app/helpers/utilisateurs_helper.rb
module UtilisateursHelper
    def gravatar_for(utilisateur) 
        gravatar_id = Digest::MD5::hexdigest(utilisateur.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: utilisateur.nom, class: "gravatar")
    end
end

app/views/layouts/_footer.html.erb
<footer>
    <p>&copy; My Business 2019 - 2019. Tous droits réservés.</p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to  image_tag("maBanner.png", alt: "logo"), root_path, class: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to  "Accueil", root_path %></li>
          <li><%= link_to  "Services", services_path %></li>
          <li><%= link_to  "Team", team_path %></li>
          <li><%= link_to  "Contact", contact_path %></li>
        </ul>
      </nav>
    </div>
  </header>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
      <title><%= yield(:title) %> | Tutoriel RoR Udemy </title>
      <%= csrf_meta_tags %>
      
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <section class="container">
      <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div> 
      <% end %>
      <%= yield %>
    </section>
    <%= render "layouts/footer" %>
    <%= debug(params) if Rails.env.development? %>
    
  </body>
</html>

app/views/shared/_error_messages.html.erb
 <% if @utilisateur.errors.any? %>
    <div class="alert alert-danger">
        Le formulaire contient <%= pluralize(@utilisateur.errors.count, "erreur") %>.
    </div>
    <ul class="list-form">
        <% @utilisateur.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
<% end %>

app/views/statique/accueil.html.erb
<% provide(:title, "Accueil") %>
<div class="center jumbotron">
    <h1>Bienvenue</h1>

    <p>&darr; Pour vous inscrire, cliquez simplement sur le bouton ci-dessous &darr;</p>

    <%= link_to  "S'inscrire maintenant", signup_url , class: "btn btn-lg btn-primary" %>
</div>

app/views/statique/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Statique#Contact</h1>

app/views/statique/services.html.erb
<% provide(:title, "Services") %>
<h1>Statique#Services</h1>

app/views/statique/team.html.erb
<% provide(:title, "Team") %>
<h1>Statique#Team</h1>

app/views/utilisateurs/new.html.erb
<% provide(:title, "S'enregistrer") %>
<h1 class="register-title">S'enregistrer</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%=form_for(@utilisateur) do |f| %>
            <%= render 'shared/error_messages' %>
            <%= f.label :nom %>
            <%= f.text_field :nom, class: 'form-control' %>
            
            <%= f.label :email %>
            <%= f.text_field :email, class: 'form-control' %>

            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>

            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>

            <%= f.submit "Créer mon compte", class: 'btn btn-primary' %>
    <% end %>  
    </div>  
</div>

app/views/utilisateurs/show.html.erb
<% provide(:title, @utilisateur.nom) %>
<div class="row">
    <aside class="col-md-4">
        <section class="info_utilisateur">
            <h1>
                <%= gravatar_for @utilisateur %>
                <%= @utilisateur.nom %>
            </h1>
        </section>
    </aside>
</div>